config/routes.rb
Rails.application.routes.draw do
  
  root to: "application#home"

  resources :books, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :book_genres
  has_many :genres, through: :book_genres

  def genre_attribute=(genre_attribute)
    genre = Genre.find_or_create_by(title: genre_attribute[:title])
    self.genres << genre if !self.genres.include?(genre)
  end
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :book_genres
  has_many :books, through: :book_genres
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home 
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController 

  def index 
    @books = Book.all
  end

  def show 
    @book = Book.find_by(id: params[:id])
    if @book
      render :show 
    else 
      redirect_to books_path
    end
  end

  def new 
    @book = Book.new
  end

  def create
    params.inspect
    @book = Book.new(book_params)
    if @book.save 
      redirect_to books_path
    else 
      render :new
    end
  end

  private 

  def book_params 
    params.require(:book).permit(:title, genre_ids: [], genre_attribute: :title)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<h1>Welcome to the book collection</h1>

app/views/books/index.html.erb
<% @books.each do |book| %>
  <div>
    <h3>Title: <%= link_to book.title, book_path(book) %></h3>
    <h4>Genres: </h4>
    <ul>
      <% book.genres.each do |genre| %>
        <li><%= genre.title %></li>
      <% end %>
    </ul>
  </div> 
<% end %>

app/views/books/new.html.erb
<h2>Add A Book</h2>

<%= form_for @book do |f| %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label "Genres" %>
    <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :title %>
  </div>

  <div>
    <%= f.fields_for :genre_attribute do |field| %>
      <%= field.label "Add New Genre" %>
      <%= field.text_field :title %>
    <% end %>
  </div>

  <%= f.submit "Yay!! New Book" %>
<% end %>

app/views/books/show.html.erb
<div>
  <h3>Title: <%= @book.title %></h3>
  <h4>Genres: </h4>
  <ul>
    <% @book.genres.each do |genre| %>
      <li><%= genre.title %></li>
    <% end %>
  </ul>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedForms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="navbar">
    <%= link_to "Home", root_path %>
    <%= link_to "Books", books_path %>
    <%= link_to "+ Book", new_book_path %>
  </div> 

    <%= yield %>
  </body>
</html>